[window]
padding = { x = 15, y = 15 }
decorations = "Transparent"
option_as_alt = "Both"

[font]
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
bold = { family = "MesloLGL Nerd Font", style = "Bold" }
italic = { family = "MesloLGL Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGL Nerd Font", style = "Bold Italic" }
size = 20

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
      { key = "ArrowLeft", mods = "Option", chars = "\u001bb" },    # Jump left a word
      { key = "ArrowRight", mods = "Option", chars = "\u001bf" },   # Jump right a word 
      { key = "ArrowLeft", mods = "Command", chars = "\u001bOH" },  # Start of line
      { key = "ArrowRight", mods = "Command", chars = "\u001bOF" }, # End of line 
      { key = "Backspace", mods = "Command", chars = "\u0015" },    # Delete line
]
