after-login-command = []
after-startup-command = [
    'exec-and-forget sketchybar --reload'
]
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       15
outer.bottom =     15
outer.top =        50
outer.right =      15


[mode.main.binding]
cmd-h = []
cmd-alt-h = []
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-leftSquareBracket = 'focus-monitor left'
alt-rightSquareBracket = 'focus-monitor right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -80'
alt-shift-equal = 'resize smart +80'
alt-shift-e = 'balance-sizes'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-n = 'workspace N'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-z = 'workspace Z'

alt-shift-1 = ['move-node-to-workspace 1', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-2 = ['move-node-to-workspace 2', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-3 = ['move-node-to-workspace 3', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-4 = ['move-node-to-workspace 4', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-9 = ['move-node-to-workspace 9', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-0 = ['move-node-to-workspace 10', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-a = ['move-node-to-workspace A', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-b = ['move-node-to-workspace B', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-n = ['move-node-to-workspace N', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-s = ['move-node-to-workspace S', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-t = ['move-node-to-workspace T', 'exec-and-forget sketchybar --trigger space_windows_change']
alt-shift-z = ['move-node-to-workspace Z', 'exec-and-forget sketchybar --trigger space_windows_change']

alt-shift-m = 'fullscreen'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


[workspace-to-monitor-force-assignment]
10 = 'secondary'
9 = 'secondary'
S = 'secondary'
N = 'secondary'
Z = 'secondary'

# default workspace for app
[[on-window-detected]]
if.app-id = 'com.microsoft.edgemac'
if.during-aerospace-startup = true
run = 'move-node-to-workspace B'
[[on-window-detected]]
if.app-id = 'org.alacritty'
if.during-aerospace-startup = true
run = 'move-node-to-workspace T'
[[on-window-detected]]
if.app-id = 'com.microsoft.onenote.mac'
run = 'move-node-to-workspace N'
[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'move-node-to-workspace N'
[[on-window-detected]]
if.app-name-regex-substring = 'Youtube Music'
run = 'move-node-to-workspace Z'


# default floating window
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.colliderli.iina'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'net.freemacsoft.AppCleaner'
run = 'layout floating'
